# Generated by Django 4.2.16 on 2024-11-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHOWROOM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
